### ISSUE TITLE
Documentation Dead Link

### ISSUE THREAD

**Issue by ghost** [RhysU/ESIO#2]
Hey!

I'm using your libraries as a dependency for another program. I wanted to extend the functionality of the host program, and in doing so, I'm looking to understand the API for your code. Unfortunately, all of the documentation links go to a dead UTexas site. Is there any way to provide the documentation on a new site or via github?!

Thanks a lot!

**Comment by RhysU** [comment]
If you need them quickly, you can build them with doxygen I believe.  I will get them updated, but it'll take me a few more days.

**Comment by ghost** [comment]
Oh! Fantastic, I didn't realize. I'll try to do that so you don't have to take too much time.

CF
Graduate Student
Aerospace Computational Design Lab
Massachusetts Institute of Technology

On Aug 31, 2016, at 7:35 AM, Rhys Ulerich <notifications@github.com<mailto:notifications@github.com>> wrote:

If you need them quickly, you can build them with doxygen I believe. I will get them updated, but it'll take me a few more days.

**Comment by RhysU** [comment]
I've updated the link-- it points to a 0.1.9 set of the documentation.  There are slight differences going to 0.2.0, but nothing crazy.

**Comment by ghost** [comment]
Gracias mucho.

CF
Graduate Student
Aerospace Computational Design Lab
Massachusetts Institute of Technology

On Aug 31, 2016, at 11:07 PM, Rhys Ulerich <notifications@github.com<mailto:notifications@github.com>> wrote:

I've updated the link-- it points to a 0.1.9 set of the documentation. There are slight differences going to 0.2.0, but nothing crazy.
