### ISSUE TITLE
Compile error on multiple machines

### ISSUE THREAD

**Issue by moprak** [RhysU/ESIO#4]
I get a bunch of errors similar to the lines below when compiling esio with gcc 6 or 7.  I'm not exactly sure what's causing the error, if it is because of the gcc version or how it can be fixed. Any ideas? I've also attached my [config.log](https://github.com/RhysU/ESIO/files/1192712/config.log.txt) and [make error output](https://github.com/RhysU/ESIO/files/1192711/make-error.txt) if that helps.
```
layout.c:170:20: error: conflicting types for 'esio_field_layout2_field_reader'
 #define METHODNAME esio_field_layout2_field_reader
```

**Comment by RhysU** [comment]
I will take a look this evening.

**Comment by moprak** [comment]
I think this might be a case of  pre-built mpich/hdf5 from the repositories on arch linux and ubuntu doing something weird. I don't see this error when I compile my own versions of those two.

**Comment by moprak** [comment]
Have tested this against both gcc 6 and gcc 7 now, not sure which of the system mpich or hdf5 is the problem but it doesn't seem like an esio bug.

**Comment by RhysU** [comment]
Sorry I didn't get the chance to look for you. Glad you got it solved.

**Comment by moprak** [comment]
Oh no worries, I was too lazy to setup lmod on my machines, this forced me to do it.
